import type { Block } from "payload";

export const OurServices: Block = {
  slug: "ourServices",
  interfaceName: "OurServicesBlock",
  fields: [
    {
      name: "isVisibleOnHomepage",
      type: "checkbox",
      label: "Show in Homepage",
      defaultValue: false,
    },
    {
      name: "title",
      type: "text",
      localized: true,
      label: "Main Title",
      required: true,
    },
    {
      name: "subtitle",
      type: "textarea",
      localized: true,
      label: "Subtitle / Introduction",
    },
    {
      name: "services",
      type: "array",
      label: "Services List",
      localized: true,
      minRows: 1,
      fields: [
        {
          name: "title",
          type: "text",
          required: true,
          label: "Service Title",
        },
        {
          name: "description",
          type: "textarea",
          label: "Short Description (shown on card)",
        },
        {
          name: "icon",
          type: "select",
          label: "Icon",
          options: [
            { label: "Stethoscope (Health)", value: "stethoscope" },
            { label: "Activity (Heartbeat)", value: "activity" },
            { label: "Eye", value: "eye" },
            { label: "Baby", value: "baby" },
            { label: "Microscope (Lab)", value: "microscope" },
            { label: "Syringe", value: "syringe" },
            { label: "Ambulance", value: "ambulance" },
            { label: "Pill", value: "pill" },
            { label: "Bone", value: "bone" },
            { label: "X-Ray (Scan)", value: "scan" },
            { label: "Heart", value: "heart" },
            { label: "Brain", value: "brain" },
            { label: "Lungs", value: "lungs" },
            { label: "Stomach", value: "stomach" },
            { label: "Kidney", value: "kidney" },
            { label: "Liver", value: "liver" },
            { label: "Ear", value: "ear" },
            { label: "Nose", value: "nose" },
            { label: "Tooth", value: "tooth" },
            { label: "Skin", value: "skin" },
            { label: "Muscle", value: "muscle" },
            { label: "Nerve", value: "nerve" },
            { label: "Blood", value: "blood" },
            { label: "DNA", value: "dna" },
            { label: "Virus", value: "virus" },
            { label: "Bacteria", value: "bacteria" },
            { label: "Fungus", value: "fungus" },
            { label: "Parasite", value: "parasite" },
            { label: "Allergy", value: "allergy" },
            { label: "Immune", value: "immune" },
            { label: "Cancer", value: "cancer" },
            { label: "Diabetes", value: "diabetes" },
            { label: "Education (Cap)", value: "education" },
            { label: "Disability (Accessibility)", value: "disability" },
            { label: "Insurance (Card)", value: "insurance" },
            { label: "Surgery (Scissors)", value: "surgery" },
            { label: "Nutrition (Salad)", value: "nutrition" },
            { label: "Lab (Flask)", value: "lab" },
            { label: "ICU (Cpu)", value: "icu" },
          ],
        },
        {
          type: "tabs",
          tabs: [
            {
              label: "Detailed Info",
              fields: [
                {
                  name: "longDescription",
                  type: "richText",
                  label: "Detailed Description",
                },
                {
                  name: "availableDoctors",
                  type: "relationship",
                  relationTo: "staffs",
                  hasMany: true,
                  localized: true,
                  label: "Doctors Specialized in this Service",
                },
                {
                  name: "timings",
                  type: "textarea",
                  label: "Service Timings / Availability",
                  admin: {
                    placeholder: "e.g., Sun - Fri: 10:00 AM - 4:00 PM",
                  },
                },
                {
                  name: "link",
                  type: "text",
                  label: "Learn More External Link (Optional)",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  labels: {
    plural: "Our Services Blocks",
    singular: "Our Services Block",
  },
};
