import "dotenv/config";
import payload, { type RequiredDataFromCollectionSlug } from "payload";
import configPromise from "../payload.config";

const staffSeedData = [
  {
    titlePrefix: "dr",
    fullName: "Kiran Tiwari",
    slug: "dr-kiran-tiwari",
    designation: "Chief Consultant Pediatrician",
    department: "paediatrics",
    roleType: "chief_consultant",
    specialization: "Paediatrics",
    employmentType: "full_time",
    joinDate: "2015-01-01",
    nmcNumber: "NMC-10234",
    phone: "9857670288",
    email: "dhaulagiri.hospital@gmail.com",
    biography: {
      root: {
        type: "root",
        children: [
          {
            type: "paragraph",
            children: [
              {
                type: "text",
                text: "Dr. Kiran Tiwari is the Chief Consultant Pediatrician at AmpipalHospital with over 15 years of experience in child healthcare.",
              },
            ],
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        version: 1,
      },
    },
    qualifications: [
      { degree: "MBBS", institution: "Kathmandu Medical College", year: 2005 },
      { degree: "MD Paediatrics", institution: "BPKIHS", year: 2010 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }, { language: "Hindi" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 1PM" },
      { day: "tuesday", hours: "9AM - 1PM" },
      { day: "thursday", hours: "2PM - 5PM" },
    ],
    address: {
      street: "Nayabazar",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Sunita Tiwari",
      relationship: "Spouse",
      emergencyPhone: "9800000001",
      emergencyEmail: "sunita.tiwari@gmail.com",
    },
    nmcExpiryDate: "2026-12-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 1,
  },
  {
    titlePrefix: "dr",
    fullName: "Amit Dhungana",
    slug: "dr-amit-dhungana",
    designation: "Consultant Anaesthesiologist",
    department: "anaesthesiology",
    roleType: "consultant",
    specialization: "Anaesthesiology",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-20341",
    email: "amitdhun@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Institute of Medicine, TU", year: 2008 },
      { degree: "MD Anaesthesiology", institution: "PGIMER Chandigarh", year: 2013 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "monday", hours: "10AM - 2PM" },
      { day: "friday", hours: "10AM - 2PM" },
    ],
    address: {
      street: "Putalisadak",
      city: "Kathmandu",
      district: "Kathmandu",
      province: "Bagmati",
      zipCode: "44600",
    },
    emergencyContact: {
      name: "Riya Dhungana",
      relationship: "Spouse",
      emergencyPhone: "9800000002",
      emergencyEmail: "riya.dhungana@gmail.com",
    },
    nmcExpiryDate: "2027-06-30",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 2,
  },
  {
    titlePrefix: "dr",
    fullName: "Sandeep Khatri",
    slug: "dr-sandeep-khatri",
    designation: "Consultant Anaesthesiologist",
    department: "anaesthesiology",
    roleType: "consultant",
    specialization: "Anaesthesiology",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-20498",
    email: "kcsanjeb44@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "BP Koirala Institute of Health Sciences", year: 2009 },
      { degree: "MD Anaesthesiology", institution: "TUTH", year: 2014 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "tuesday", hours: "9AM - 1PM" },
      { day: "saturday", hours: "9AM - 1PM" },
    ],
    address: {
      street: "Lakeside",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Anjali Khatri",
      relationship: "Spouse",
      emergencyPhone: "9800000003",
      emergencyEmail: "anjali.khatri@gmail.com",
    },
    nmcExpiryDate: "2027-03-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 3,
  },
  {
    titlePrefix: "dr",
    fullName: "Pramesh Thapa",
    slug: "dr-pramesh-thapa",
    designation: "Consultant Orthopedics Surgeon",
    department: "orthopedics",
    roleType: "consultant",
    specialization: "Orthopedic Surgery",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-30512",
    email: "prameshthapa4444@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Manipal College of Medical Sciences", year: 2007 },
      { degree: "MS Orthopedics", institution: "AIIMS New Delhi", year: 2012 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }, { language: "Hindi" }],
    availabilitySchedule: [
      { day: "wednesday", hours: "10AM - 3PM" },
      { day: "saturday", hours: "10AM - 1PM" },
    ],
    address: {
      street: "Prithvi Chowk",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Sita Thapa",
      relationship: "Spouse",
      emergencyPhone: "9800000004",
      emergencyEmail: "sita.thapa@gmail.com",
    },
    nmcExpiryDate: "2026-09-30",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 4,
  },
  {
    titlePrefix: "dr",
    fullName: "Anil Prasad Pokhrel",
    slug: "dr-anil-prasad-pokhrel",
    designation: "Consultant Orthopedics Surgeon",
    department: "orthopedics",
    roleType: "consultant",
    specialization: "Orthopedic Surgery",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-30678",
    email: "meaneel2010@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Tribhuvan University Teaching Hospital", year: 2006 },
      { degree: "MS Orthopedics", institution: "PGIMER Chandigarh", year: 2011 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "monday", hours: "9AM - 1PM" },
      { day: "thursday", hours: "9AM - 1PM" },
    ],
    address: {
      street: "Mahendrapool",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Mina Pokhrel",
      relationship: "Spouse",
      emergencyPhone: "9800000005",
      emergencyEmail: "mina.pokhrel@gmail.com",
    },
    nmcExpiryDate: "2027-01-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 5,
  },
  {
    titlePrefix: "dr",
    fullName: "Bijaya Ojha",
    slug: "dr-bijaya-ojha",
    designation: "Consultant Obs and Gynaecologist",
    department: "obs_gynae",
    roleType: "consultant",
    specialization: "Obstetrics & Gynaecology",
    employmentType: "full_time",
    nmcNumber: "NMC-40321",
    email: "ojhabijay12@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Kathmandu Medical College", year: 2008 },
      { degree: "MD Obstetrics & Gynaecology", institution: "TUTH", year: 2013 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 5PM" },
      { day: "tuesday", hours: "9AM - 5PM" },
      { day: "thursday", hours: "9AM - 5PM" },
    ],
    address: {
      street: "Bagar",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Suresh Ojha",
      relationship: "Spouse",
      emergencyPhone: "9800000006",
      emergencyEmail: "suresh.ojha@gmail.com",
    },
    nmcExpiryDate: "2026-08-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 6,
  },
  {
    titlePrefix: "dr",
    fullName: "Shankar Raj Lamichane",
    slug: "dr-shankar-raj-lamichane",
    designation: "Consultant Surgeon",
    department: "general_surgery",
    roleType: "consultant",
    specialization: "General Surgery",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-50234",
    email: "shankarlc11@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "KIST Medical College", year: 2007 },
      { degree: "MS General Surgery", institution: "TUTH", year: 2012 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "monday", hours: "10AM - 2PM" },
      { day: "wednesday", hours: "10AM - 2PM" },
    ],
    address: {
      street: "Nadipur",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Kamala Lamichane",
      relationship: "Spouse",
      emergencyPhone: "9800000007",
      emergencyEmail: "kamala.lamichane@gmail.com",
    },
    nmcExpiryDate: "2027-05-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 7,
  },
  {
    titlePrefix: "dr",
    fullName: "Aashish Bastakoti",
    slug: "dr-aashish-bastakoti",
    designation: "Consultant Surgeon",
    department: "general_surgery",
    roleType: "consultant",
    specialization: "General Surgery",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-50456",
    email: "bastakoteaaashish111@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Gandaki Medical College", year: 2009 },
      { degree: "MS General Surgery", institution: "BP Koirala Institute", year: 2014 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "tuesday", hours: "10AM - 3PM" },
      { day: "friday", hours: "10AM - 3PM" },
    ],
    address: {
      street: "Srijana Chowk",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Nisha Bastakoti",
      relationship: "Spouse",
      emergencyPhone: "9800000008",
      emergencyEmail: "nisha.bastakoti@gmail.com",
    },
    nmcExpiryDate: "2026-11-30",
    nmcVerified: false,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 8,
  },
  {
    titlePrefix: "dr",
    fullName: "Asmita Shrestha",
    slug: "dr-asmita-shrestha",
    designation: "Consultant E.N.T. Surgeon",
    department: "ent",
    roleType: "consultant",
    specialization: "ENT Surgery",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-60123",
    email: "asmita.jn04@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Manipal College of Medical Sciences", year: 2010 },
      { degree: "MS ENT", institution: "TUTH", year: 2015 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "wednesday", hours: "9AM - 1PM" },
      { day: "saturday", hours: "9AM - 12PM" },
    ],
    address: {
      street: "Chipledhunga",
      city: "Pokhara",
      district: "Kaski",
      province: "Gandaki",
      zipCode: "33700",
    },
    emergencyContact: {
      name: "Rohan Shrestha",
      relationship: "Spouse",
      emergencyPhone: "9800000009",
      emergencyEmail: "rohan.shrestha@gmail.com",
    },
    nmcExpiryDate: "2027-04-30",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 9,
  },
  {
    titlePrefix: "dr",
    fullName: "Sandeep Sapkota",
    slug: "dr-sandeep-sapkota",
    designation: "Consultant General Physician",
    department: "general_medicine",
    roleType: "consultant",
    specialization: "General Medicine",
    employmentType: "full_time",
    nmcNumber: "NMC-70234",
    email: "sadvab1@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Pokhara University", year: 2010 },
      { degree: "MD Internal Medicine", institution: "PGIMER", year: 2015 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }, { language: "Hindi" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 5PM" },
      { day: "monday", hours: "9AM - 5PM" },
      { day: "wednesday", hours: "9AM - 5PM" },
      { day: "friday", hours: "9AM - 5PM" },
    ],
    address: {
      street: "Gharipatan",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Puja Sapkota",
      relationship: "Spouse",
      emergencyPhone: "9800000010",
      emergencyEmail: "puja.sapkota@gmail.com",
    },
    nmcExpiryDate: "2027-02-28",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 10,
  },
  {
    titlePrefix: "dr",
    fullName: "Seshkanta Lamichhane",
    slug: "dr-seshkanta-lamichhane",
    designation: "Consultant General Physician",
    department: "general_medicine",
    roleType: "consultant",
    specialization: "General Medicine",
    employmentType: "full_time",
    nmcNumber: "NMC-70456",
    email: "lamichhanesk1312@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Nobel Medical College", year: 2009 },
      { degree: "MD Internal Medicine", institution: "TUTH", year: 2014 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "tuesday", hours: "9AM - 5PM" },
      { day: "thursday", hours: "9AM - 5PM" },
      { day: "saturday", hours: "9AM - 1PM" },
    ],
    address: {
      street: "Dhawalagiri Chowk",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Sabita Lamichhane",
      relationship: "Spouse",
      emergencyPhone: "9800000011",
      emergencyEmail: "sabita.lamichhane@gmail.com",
    },
    nmcExpiryDate: "2026-10-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 11,
  },
  {
    titlePrefix: "dr",
    fullName: "Kushal Gurung",
    slug: "dr-kushal-gurung",
    designation: "Consultant Ophthalmologist",
    department: "ophthalmology",
    roleType: "consultant",
    specialization: "Ophthalmology",
    employmentType: "visiting_consultant",
    nmcNumber: "NMC-80123",
    email: "skeins35@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Gandaki Medical College", year: 2010 },
      { degree: "MS Ophthalmology", institution: "BPKIHS", year: 2015 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "monday", hours: "10AM - 2PM" },
      { day: "thursday", hours: "10AM - 2PM" },
    ],
    address: {
      street: "Pardi",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Sarita Gurung",
      relationship: "Spouse",
      emergencyPhone: "9800000012",
      emergencyEmail: "sarita.gurung@gmail.com",
    },
    nmcExpiryDate: "2027-07-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 12,
  },
  {
    titlePrefix: "dr",
    fullName: "Bipana K.C.",
    slug: "dr-bipana-kc",
    designation: "Consultant Medical Generalist",
    department: "internal_medicine",
    roleType: "consultant",
    specialization: "Internal Medicine",
    employmentType: "full_time",
    nmcNumber: "NMC-90234",
    email: "bip.kessy@gmail.com",
    qualifications: [
      {
        degree: "MBBS",
        institution: "Kathmandu University School of Medical Sciences",
        year: 2011,
      },
      { degree: "MD Internal Medicine", institution: "TUTH", year: 2016 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 5PM" },
      { day: "wednesday", hours: "9AM - 5PM" },
      { day: "friday", hours: "9AM - 5PM" },
    ],
    address: {
      street: "Timilsena Tole",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Bikram K.C.",
      relationship: "Spouse",
      emergencyPhone: "9800000013",
      emergencyEmail: "bikram.kc@gmail.com",
    },
    nmcExpiryDate: "2026-07-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 13,
  },
  {
    titlePrefix: "dr",
    fullName: "Yashoda Poudel",
    slug: "dr-yashoda-poudel",
    designation: "Consultant Paediatrician",
    department: "paediatrics",
    roleType: "consultant",
    specialization: "Paediatrics",
    employmentType: "full_time",
    nmcNumber: "NMC-10567",
    email: "yashodapoudel178@gmail.com",
    qualifications: [
      { degree: "MBBS", institution: "Manipal College of Medical Sciences", year: 2012 },
      { degree: "MD Paediatrics", institution: "BPKIHS", year: 2017 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 1PM" },
      { day: "monday", hours: "9AM - 1PM" },
      { day: "thursday", hours: "2PM - 5PM" },
    ],
    address: {
      street: "Baglung Bazar",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Naresh Poudel",
      relationship: "Spouse",
      emergencyPhone: "9800000014",
      emergencyEmail: "naresh.poudel@gmail.com",
    },
    nmcExpiryDate: "2027-08-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 14,
  },
  {
    titlePrefix: "ms",
    fullName: "Shanti Paudel",
    slug: "shanti-paudel",
    designation: "Hospital Nursing Administrator",
    department: "nursing_admin",
    roleType: "administrator",
    specialization: "Nursing Administration",
    employmentType: "full_time",
    nmcNumber: "NNC-00123",
    phone: "9848666008",
    email: "dhaulagiri.suchana@gmail.com",
    qualifications: [
      { degree: "B.Sc Nursing", institution: "Pokhara University", year: 2008 },
      { degree: "MPH", institution: "Tribhuvan University", year: 2013 },
    ],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 5PM" },
      { day: "monday", hours: "9AM - 5PM" },
      { day: "tuesday", hours: "9AM - 5PM" },
      { day: "wednesday", hours: "9AM - 5PM" },
      { day: "thursday", hours: "9AM - 5PM" },
    ],
    address: {
      street: "Phalebas",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Ram Paudel",
      relationship: "Spouse",
      emergencyPhone: "9800000015",
      emergencyEmail: "ram.paudel@gmail.com",
    },
    nmcExpiryDate: "2027-09-30",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 15,
  },
  {
    titlePrefix: "dr",
    fullName: "Srijana Aryal",
    slug: "dr-srijana-aryal",
    designation: "Medical Officer",
    department: "general_medicine",
    roleType: "medical_officer",
    specialization: "General Medicine",
    employmentType: "full_time",
    nmcNumber: "NMC-11234",
    email: "srijanaaryal03@gmail.com",
    qualifications: [{ degree: "MBBS", institution: "Gandaki Medical College", year: 2016 }],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "sunday", hours: "9AM - 5PM" },
      { day: "tuesday", hours: "9AM - 5PM" },
      { day: "thursday", hours: "9AM - 5PM" },
      { day: "saturday", hours: "9AM - 1PM" },
    ],
    address: {
      street: "Baliphai",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Sujan Aryal",
      relationship: "Spouse",
      emergencyPhone: "9800000016",
      emergencyEmail: "sujan.aryal@gmail.com",
    },
    nmcExpiryDate: "2027-10-31",
    nmcVerified: true,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 16,
  },
  {
    titlePrefix: "dr",
    fullName: "Nischal Shrestha",
    slug: "dr-nischal-shrestha",
    designation: "Medical Officer",
    department: "general_medicine",
    roleType: "medical_officer",
    specialization: "General Medicine",
    employmentType: "full_time",
    nmcNumber: "NMC-11567",
    email: "shresthasnisal@gmail.com",
    qualifications: [{ degree: "MBBS", institution: "Pokhara University", year: 2017 }],
    languagesSpoken: [{ language: "Nepali" }, { language: "English" }],
    availabilitySchedule: [
      { day: "monday", hours: "9AM - 5PM" },
      { day: "wednesday", hours: "9AM - 5PM" },
      { day: "friday", hours: "9AM - 5PM" },
      { day: "saturday", hours: "9AM - 1PM" },
    ],
    address: {
      street: "Arkhale",
      city: "Baglung",
      district: "Baglung",
      province: "Gandaki",
      zipCode: "33200",
    },
    emergencyContact: {
      name: "Priya Shrestha",
      relationship: "Spouse",
      emergencyPhone: "9800000017",
      emergencyEmail: "priya.shrestha@gmail.com",
    },
    nmcExpiryDate: "2027-11-30",
    nmcVerified: false,
    isActive: true,
    showOnWebsite: true,
    displayOrder: 17,
  },
];

async function seedStaffs(): Promise<void> {
  try {
    await payload.init({ config: configPromise });

    // Give Payload some time to build indexes or sync schemas which locks the DB
    console.log("⏳ Waiting 10s for MongoDB index locks to clear...");
    await new Promise((resolve) => setTimeout(resolve, 10000));

    console.log("🌱 Starting staff seeder...");

    // Clear existing staff records
    const existing = await payload.find({ collection: "staffs", limit: 100 });
    if (existing.docs.length > 0) {
      console.log(`🗑️  Deleting ${existing.docs.length} existing staff records...`);
      for (const doc of existing.docs) {
        await payload.delete({ collection: "staffs", id: doc.id });
      }
    }

    // Insert all staff
    const results = [];
    for (const staff of staffSeedData) {
      results.push(
        await payload.create({
          collection: "staffs",
          data: staff as unknown as RequiredDataFromCollectionSlug<"staffs">,
        })
      );
    }

    console.log(`✅ Successfully seeded ${results.length} staff members:`);
    results.forEach((r) =>
      console.log(`   • ${r.titlePrefix.toUpperCase()}. ${r.fullName} — ${r.designation}`)
    );
  } catch (error) {
    console.error("❌ Seeder failed:", error);
    process.exit(1);
  } finally {
    process.exit(0);
  }
}

seedStaffs();
